import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./layout.css";
import { Navigator } from "./components/Navigator";
import { ProviederContext } from "./context/contex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviederContext>
          <div className="mainConteiner">
            <div className="title">
              <h1>Esto rick y la ulitma por fin.</h1>
            </div>
            <Navigator />
            {children}
          </div>
        </ProviederContext>
      </body>
    </html>
  );
}
